<?php
use CRM_CivicrmAdminUi_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Membership_Types',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Membership_Types',
        'label' => E::ts('Membership Types'),
        'api_entity' => 'MembershipType',
        'api_params' => [
          'version' => 4,
          'select' => [
            'name',
            'period_type:label',
            'fixed_period_start_day',
            'duration_interval',
            'duration_unit:label',
            'minimum_fee',
            'auto_renew:label',
            'relationship_type_id',
            'max_related',
            'visibility:label',
            'is_active',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Membership_Types_SearchDisplay_Membership_Types_Table_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Membership_Types_Table_1',
        'label' => E::ts('Membership Types Table 1'),
        'saved_search_id.name' => 'Membership_Types',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [],
          'limit' => 50,
          'pager' => [
            'hide_single' => TRUE,
          ],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'name',
              'dataType' => 'String',
              'label' => E::ts('Membership'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'period_type:label',
              'dataType' => 'String',
              'label' => E::ts('Period'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'fixed_period_start_day',
              'dataType' => 'Integer',
              'label' => E::ts('Fixed Start'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'duration_interval',
              'dataType' => 'Integer',
              'label' => E::ts('Duration'),
              'sortable' => TRUE,
              'rewrite' => '[duration_interval] [duration_unit:label]',
            ],
            [
              'type' => 'field',
              'key' => 'minimum_fee',
              'dataType' => 'Money',
              'label' => E::ts('Minimum Fee'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'auto_renew:label',
              'dataType' => 'Integer',
              'label' => E::ts('Auto-Renew'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'relationship_type_id',
              'dataType' => 'String',
              'label' => E::ts('Related'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'max_related',
              'dataType' => 'Integer',
              'label' => E::ts('Max'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'visibility:label',
              'dataType' => 'String',
              'label' => E::ts('Visibility'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_active',
              'dataType' => 'Boolean',
              'label' => E::ts('Enabled?'),
              'sortable' => TRUE,
            ],
            [
              'text' => '',
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'entity' => 'MembershipType',
                  'action' => 'update',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Update'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                ],
                [
                  'task' => 'enable',
                  'entity' => 'MembershipType',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-on',
                  'text' => E::ts('Enable'),
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => [
                    'is_active',
                    '=',
                    FALSE,
                  ],
                ],
                [
                  'task' => 'disable',
                  'entity' => 'MembershipType',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-off',
                  'text' => E::ts('Disable'),
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => [
                    'is_active',
                    '=',
                    TRUE,
                  ],
                ],
                [
                  'task' => 'delete',
                  'entity' => 'MembershipType',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'path' => '',
                  'action' => '',
                  'condition' => [],
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => FALSE,
          'classes' => [
            'table',
            'table-striped',
          ],
          'draggable' => 'weight',
          'toolbar' => [
            [
              'entity' => 'MembershipType',
              'action' => 'add',
              'join' => '',
              'target' => 'crm-popup',
              'icon' => 'fa-plus',
              'text' => E::ts('Add'),
              'style' => 'primary',
              'path' => '',
              'task' => '',
              'condition' => [],
            ],
          ],
          'cssRules' => [
            [
              'disabled',
              'is_active',
              '=',
              FALSE,
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
